### ISSUE TITLE
Wasted bits:  HashAndSignatureAlgorithm

### ISSUE THREAD

**Issue by MikeBishop** [MikeBishop/http2-client-certs#3]
HashAndSignatureAlgorithm is a sixteen-bit value, but allowed values are currently limited to sixteen (i.e. 4 bits).  Keep the current length so we can reuse TLS-defined values, or shave?  Even if we need to overflow into additional SETTINGS values someday, eight bits seems more than sufficient.

**Comment by martinthomson** [comment]
I don't think that this level of waste is worth worrying about.

**Comment by MikeBishop** [comment]
Moot (for now, until we fix #12).
